[tool.poetry]
name = "mkdocs-sandbox"
version = "0.1.0"
description = ""
authors = ["Masaki Itoh"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-with-pdf = "^0.9.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
